### ISSUE TITLE
Website content

### ISSUE THREAD

**Issue by abbeyjackson** [UnanimousWorld/org#30]
Create a document with website content so that each person has a chance to edit the information before Renato makes our basic website

**Website content**: https://drive.google.com/drive/folders/0B7AilusWlJgMN3NEblZoNTNSZnc

**Comment by renatomcamilio** [comment]
https://docs.google.com/document/d/1j-ykdUmc5vVttOHZQRWnEphXP9IWJeTPUz6Sr208mHA/edit#heading=h.193dcvodwt5q

**Comment by abbeyjackson** [comment]
@renatomcamilio Will you close this when you get the content online or do you want to make a new issue for that and I can close this now?

**Comment by abbeyjackson** [comment]
@renatomcamilio what is your timeline with the webpage? There is no deadline I just would like an idea of where you're at / when to expect it.

**Comment by renatomcamilio** [comment]
@abbeyjackson working on it, should have it ready by EOD today! ty for the remind!

**Comment by abbeyjackson** [comment]
Closing this issue as we have the content in a doc
